export const LOG_IN_USER = "LOG_IN_USER";

export const LOG_OUT_USER = "LOG_OUT_USER";

export const USER_SIGN_UP_ERROR = "USER_SIGN_UP_ERROR";

export const USER_SIGN_UP = "USER_SIGN_UP";

export const USER_LOG_IN_ERROR = "USER_LOG_IN_ERROR";

export const ADD_FAVORITE_CHARACTER = "ADD_FAVORITE_CHARACTER";

export const DELETE_FAVORITE_CHARACTER = "DELETE_FAVORITE_CHARACTER";
